/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Luv' at '19/09/19 16:46' with Gradle 2.14.1
 *
 * @author Luv, @date 19/09/19 16:46
 */
public class Library {
    public boolean someLibraryMethod() {
    	// aa t
        return true;
    }
}
